[package]
name = "ufo"
version = "0.1.0"
authors = ["Dylan DPC<dylan.dpc@gmail.com>"]
edition = "2018"
description = "unsigned floats"
license = "MIT or Apache-2.0"

[dependencies]
serde = { version = "1", optional = true }

[features]
nightly = []